language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: ffN9YdRR+XEAzr8GbJnfxLNQ4snzR4dwPDEpWRIdK8eUPFTj1PCuR4Vv4d7wFWV07uc1l0tNcdrJXHNdYWrgVVxk17D3AkjWQ6gL697fxStFhMtEciUIKVmzp+jPH1Q7I+3BZHc77SEgoLuqSmbqsy0rwXPVdgA0uk99ZRqULQ8=
  on:
    tags: true
    repo: noflo/noflo-yaml
