# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 4.2

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install
  - npm grunt-cli -g

build: off
  
test_script:
  - node --version
  - npm --version
  - cmd: npm test --no-color
